### ISSUE TITLE
How to create a generator with a random seed

### ISSUE THREAD

**Issue by lpil** [giacomocavalieri/prng#1]
Hello!

How do I create a random seed with this package to not always get the same generated values?

Thanks!

**Comment by giacomocavalieri** [comment]
Hello there!
Have you looked at [`random.random_sample`](https://hexdocs.pm/prng/prng/random.html#random_sample) and [`random.to_random_iterator`](https://hexdocs.pm/prng/prng/random.html#to_random_iterator)? Those are the go to I'd recommend to get truly random values out of generators, are those two function enough for your needs or do you feel like the package is missing something?

Anyways, thanks for pointing it out! I forgot about exposing a way to generate random seeds, I've just release v2.0.0 where the `seed` module now has a `random` function to generate truly random seeds. If the functions I suggested you above are not enough for your use case you could make use of that :)

**Comment by lpil** [comment]
Oh I see! Thank you. I did read the README but I got confused as to how actually get random values, likely due to not paying enough attention.
