### ISSUE TITLE
Random strings, bit arrays, lists, and maps

### ISSUE THREAD

**Issue by lpil** [giacomocavalieri/prng#2]
Hello!

It would be fab to have generators for these types too

Thanks

**Comment by giacomocavalieri** [comment]
Yeah it would be really nice to have those directly in the package. As for list there is already a generator for lists of a fixed size, do you think that a generator for random-sized lists would be a nice addition as well?

**Comment by lpil** [comment]
Yes for sure! I'm sure different lengths will be useful for finding bugs in many cases.

**Comment by giacomocavalieri** [comment]
With v3.0.0 I should have added all the Strings and BitArray APIs are still a bit bare-bone, but I feel like they can already cover most simple use cases :)

Let me know if it looks good to you!

**Comment by lpil** [comment]
Amazing thank you
