### ISSUE TITLE
random.weighted function with integer weights

### ISSUE THREAD

**Issue by mooreryan** [giacomocavalieri/prng#8]
One bottleneck for qcheck performance is coming from the [random.weighted](https://hexdocs.pm/prng/prng/random.html#weighted) function.

It turns out that if you use `Int` for weights rather than `Float`, you can increase the speed by about 2x and, if you are careful with generating the correct integers, keep the distribution (pretty much) as "random" as the `Float` based implementation.

Potentially, would you be interested in adding a new function `random.weighted` that takes `Int` weights?

## Benchmark

Here is a benchmark comparing the two versions.  You can see that using `Int` for the weights is about 2x as fast.

<img src="https://github.com/giacomocavalieri/prng/assets/3172014/24bae9e0-6a27-4060-904d-ac3731932122" alt="bench_weighted_2" width="300"/>

## Distribution

And here is an example using both the float and int version to generate random months that are evenly distributed.  As you see the Int based weights are a bit noisier, but nothing too shocking there.

![dist_weighted_2](https://github.com/giacomocavalieri/prng/assets/3172014/06779c98-b514-4bb5-93eb-7709a3598882)

This figure is mainly to show that using `Int` for weight is okay as well.

---

I can put all the code for the benchmark and figures in some place to share it if you are interested.

**Comment by giacomocavalieri** [comment]
Hello! Thanks for pointing it out, how would you call such a function? `random.weighted_int`? It doesn't sound great but it could work. Also could you share the code you've written (a PR would be great 😁💕)

**Comment by mooreryan** [comment]
I was thinking about this some more and I think having both `weighted` and `weighted_int` may be a bit confusing for the `prng` user, as their behavior is subtly different.

For example, due to the implementation of the `random.float` generator, this test will always pass:

```gleam
pub fn multiplier_test() {
  let multiplier = random.float(1.0, 1000.0)

  let g1 =
    multiplier
    |> random.then(fn(y) {
      random.float(0.0, 1.0)
      |> random.map(fn(x) { x *. y })
    })

  let g2 =
    multiplier
    |> random.then(random.float(0.0, _))

  behaves_loosely_equal(g1, g2)
}

import gleam/float

fn behaves_loosely_equal(gen1: Generator(Float), gen2: Generator(Float)) -> Nil {
  let seed =
    random.int(random.min_int, random.max_int)
    |> random.map(seed.new)
    |> random.random_sample

  let samples1 =
    random.to_iterator(gen1, seed)
    |> iterator.take(1000)
    |> iterator.to_list
  let samples2 =
    random.to_iterator(gen2, seed)
    |> iterator.take(1000)
    |> iterator.to_list

  list.zip(samples1, samples2)
  |> list.fold(True, fn(acc, ab) {
    acc && float.loosely_equals(ab.0, ab.1, tolerating: 0.00000000001)
  })
  |> should.be_true
}
```

Which is why the test you wrote here, will work:

```gleam
pub fn uniform_behaves_like_weighted_when_all_weights_are_equal_test() {
  let gen1 = random.uniform("Luois", ["Glob", "Hayleigh", "Ben"])
  let gen2 =
    random.weighted(#(2.2, "Luois"), [
      #(2.2, "Glob"),
      #(2.2, "Hayleigh"),
      #(2.2, "Ben"),
    ])
  behaves_the_same(gen1, gen2)
}
```

However, the same property will NOT hold with the `weighted_int` generator (due to the way `random.int` itself works).  E.g., it is not the case that generators `g1`, `g2`, and `g3` will yield the same stream of values, even though their seed is the same and they each specify a uniform distribution.

```gleam
type Letters { 
  A
  B
  C
}

let g1 = random.weighted_int(#( 1, A), #( 1, B), #( 1, C)) |> random.to_iterator(seed.new(1234))
let g2 = random.weighted_int(#(10, A), #(10, B), #(10, C)) |> random.to_iterator(seed.new(1234))
let g3 = random.weighted_int(#(22, A), #(22, B), #(22, C)) |> random.to_iterator(seed.new(1234))
```

What do you think?

**Comment by giacomocavalieri** [comment]
Yeah I was afraid this could be the case... I think I'll hold off adding this to prng and see if others feel the need for something similar
