### ISSUE TITLE
Ability to define custom generators

### ISSUE THREAD

**Issue by lucaspellegrinelli** [giacomocavalieri/prng#9]
Hello!

I would like to define my own custom generators using this library. However, I noticed that the `Generator` type is `opaque`, which seems to prevent this. I am curious about the rationale behind making `Generator` opaque and if there are any ways to define custom generators.

### Why?

I am currently working on a project where I need to implement dice roll mechanics, such as "dice explosion." This involves rolling `n` dice and rerolling dice based on specific conditions (e.g., rerolling up to the number of maximum values rolled). 

Here’s a specific example using d10 dice:
- Initial roll: [10, 4, 5, 5, 2]
- Since there is one maximum value (10), I get to reroll one additional dice.

Below is an example of the usage I am aiming for:

```gleam
let seed = seed.new(0)

random.int(1, 10)
|> dice_explosion(5)
|> random.sample(seed)
|> io.debug // [10, 8, 7, 3, 4, 1]
```

In this example, we asked for 5 dice in the `dice_explosion` call, but the output has a length of 6 due to rerolling the 10.

Here’s a potential implementation for the `dice_explosion` (I took inspiration from the [`fixed_size_list` implementation](https://github.com/giacomocavalieri/prng/blob/f5f596499869e228c0ea6eed339dc724a1ece2b8/src/prng/random.gleam#L544)):

```gleam
fn do_dice_explosion(
  acc: List(Int),
  seed: Seed,
  generator: Generator(Int),
  length: Int,
) -> #(List(Int), Seed) {
  case length {
    0 -> #(acc, seed)
    n -> {
      let #(roll, next_seed) =
        generator
        |> random.fixed_size_list(n)
        |> random.step(seed)

      // This example isn't generic on the random.int range of values, but illustrates the concept
      let rerolls = roll |> list.filter(fn(x) { x == 10 }) |> list.length 

      do_dice_explosion(list.concat([acc, roll]), next_seed, generator, rerolls)
    }
  }
}

fn dice_explosion(generator: Generator(Int), n: Int) -> Generator(List(Int)) {
  use seed <- Generator
  do_dice_explosion([], seed, generator, n)
}
```

But this requires me to create a `Generator` via `use seed <- Generator`, which is not possible with the current implementation since `Generator` type is `opaque`.

### Questions

1. Why is the `Generator` type defined as `opaque`?
3. Is there an alternative approach to achieve similar functionality? I was not able to find an alternative where I could get the updated `seed` from the previous piped generator, update it throughout the dice rolling process and pass it down to the next piped function.

Thank you!

**Comment by giacomocavalieri** [comment]
Hello! Thanks for asking, this is the perfect use case for `random.then`: I'd write something like this
```gleam
pub type Dice {
  Dice(faces: Int)
}

pub fn explosive_roll(dice: Dice) -> Random(List(Int)) {
  let initial_rolls_size = 5
  use initial_rolls <- random.then(roll(dice, initial_rolls_size))
  //  ^^^^^^^^^^^^^ Thanks to `then` we have access to the randomly
  //                generated sequence and can decide how to go on
  //                and what to return.

  let additional_rolls_size =
    count(initial_rolls, fn(roll) { roll == dice.faces })

  use additional_rolls <- random.then(roll(dice, additional_rolls))
  //  ^^^^^^^^^^^^^^^^ Once again, thanks to `then` we also have the
  //                   randomly generated additional rolls.

  random.constant(list.append(initial_rolls, additional_rolls))
  //     ^^^^^^^^ In the end we must still return a generator, not
  //              just a list, so we can wrap the randomly generated
  //              list in a `constant` generator.
}

pub fn roll(dice: Dice, times n: Int) -> List(Int) {
  random.fixed_size_list(n, from: random.int(1, dice.faces))
}
```

In general, when you need to combine simple generators into more complex ones you'll want to reach for `map`, `map2`, ... and `then` (which is the most powerful one as it gives you the ability to access the randomly generated value and decide what to generate based on its actual value).

I hope this helps!

**Comment by lucaspellegrinelli** [comment]
That is exactly what I was looking for, thank you so much! I had experimented with `.then`, but the idea of nesting them in the way you showed never crossed my mind. As a result, I was composing functions in a way that didn't make much sense and didn't really worked out. But the solution was so simple all along!

Now I can also see the full power of `then`, in the docs you mentioned how powerful it was but now it clicked in my head. Thanks a lot again!

**Comment by giacomocavalieri** [comment]
You're welcome! Always happy to help 💕
